#!/usr/bin/env bash

# Exit on error
set -e

set -x

if [ -z "$1" ] || [ -z "$2" ]; then
  echo "Usage: ./create <type_of_post> \"<Title Of Post>\""
  exit 1
fi

# Generate timestamp
TIMESTAMP=$(date +"%Y-%m-%d-%H%M")

TYPE_OF_POST="$1"

# Convert title to slug
TITLE="$2"
SLUG=$(echo "$TITLE" \
  | tr '[:upper:]' '[:lower:]' \
  | sed -E 's/[^a-z0-9]+/-/g' \
  | sed -E 's/^-+|-+$//g')

FILENAME="${TIMESTAMP}-${SLUG}.md"

# Create new Hugo post
if [[ $TYPE_OF_POST == "blog" ]]; then
    hugo new "stickies/${FILENAME}"
    echo "Created stickies/${FILENAME}"
else
    hugo new "${FILENAME}"
    echo "Created ${FILENAME}"
fi
